### ISSUE TITLE
Does this plugin generate new provisioning profiles?

### ISSUE THREAD

**Issue by tundsD53** [HIIgor/match_certs_migration#2]
Does this plugin have the capability to generate new provisioning profiles using the existing certificate, it's found on the Apple Developer Centre? I've saw that it fetches profiles but nothing about generating them.

**Comment by HIIgor** [comment]
@tundsD53  As you see, it will only reuse the certificate. After migration you can use match to fetch the profiles, and remember to set readonly to false.

**Comment by tundsD53** [comment]
@HIIgor You see the issue/dilemma i’m having is that in some cases the profiles don’t already exist since it’s a brand new project so there is nothing to fetch, so i need to be able to create new profiles using the existing cert. As for the profiles that have been signed and already exist they can be left untouched and just use the current/existing cert

**Comment by HIIgor** [comment]
@tundsD53 Thanks for reply. The match will generate profiles using the current/existing cert，have you tried it or have you had any problems

**Comment by tundsD53** [comment]
@HIIgor It seems to be hanging on this command line.

`[14:01:32]: current_git_dir -> /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/d20180909-41408-5hpzx9`

**Comment by HIIgor** [comment]
@tundsD53  I'm wandering if there was an error when cloning the repo, maybe git configure is needed. Can you support some more information about this please?

**Comment by tundsD53** [comment]
@HIIgor Could it be because the repo where I have my certificates saved is a private repo?, this the command on verbose it seems to be stuck on. 

`INFO [2018-09-09 14:28:21.76]: $ git clone 'https://tunds@bitbucket.org/tunds/fastlane-example-certificates.git' '/var/folders/ct/gsm1gpw96nsc1qrr2z4x3nd80000gp/T/d20180909-42126-1v3vi8v'`

Seems like it's struggling to clone the repo into the temp folder for some reason using https

**Comment by HIIgor** [comment]
@tundsD53  YES, it seems to be. can you run the command manually to make sure you're properly authenticated: `git clone 'https://tunds@bitbucket.org/tunds/fastlane-example-certificates.git' '/var/folders/ct/gsm1gpw96nsc1qrr2z4x3nd80000gp/T/d20180909-42126-1v3vi8v' ` 
And did this problem occur when you were using match?

**Comment by tundsD53** [comment]
So i've switched the repo to public and that has removed that error but now i'm getting the following error within the console.

`bundler: failed to load command: fastlane (/usr/local/bin/fastlane)`
xxxxxxx:fastlaneexample xxxxxx$ bundle exec fastlane test_cert_migration --verbose
[✔] 🚀
Successfully loaded Appfile at path '/Users/xxxxx/Documents/Fastlane/fastlaneexample/fastlane/Appfile'
- app_identifier: 'xxxx.xxxxxx'
- apple_id: 'xxxxxx@xxx.com'
- team_id: 'xxxxxxxx'
-------
INFO [2018-09-10 15:46:20.84]: Successfully loaded custom action '/Users/Tunde/Documents/Fastlane/fastlaneexample/fastlane/actions/match_certs_migration.rb'.
DEBUG [2018-09-10 15:46:20.85]: Checking if there are any plugins that should be loaded...
DEBUG [2018-09-10 15:46:20.85]: Loading 'fastlane-plugin-update_project_codesigning' plugin
INFO [2018-09-10 15:46:20.85]: gem 'fastlane-plugin-update_project_codesigning' is already installed
+--------------------------------------------+---------+----------------------------+
|                                   Used plugins                                    |
+--------------------------------------------+---------+----------------------------+
| Plugin                                     | Version | Action                     |
+--------------------------------------------+---------+----------------------------+
| fastlane-plugin-update_project_codesigning | 0.2.0   | update_project_codesigning |
+--------------------------------------------+---------+----------------------------+

INFO [2018-09-10 15:46:21.17]: ----------------------------------------
INFO [2018-09-10 15:46:21.17]: --- Step: Verifying fastlane version ---
INFO [2018-09-10 15:46:21.17]: ----------------------------------------
INFO [2018-09-10 15:46:21.17]: Your fastlane version 2.104.0 matches the minimum requirement of 2.62.0  ✅
INFO [2018-09-10 15:46:21.17]: ---------------------------
INFO [2018-09-10 15:46:21.17]: --- Step: opt_out_usage ---
INFO [2018-09-10 15:46:21.17]: ---------------------------
INFO [2018-09-10 15:46:21.17]: Disabled upload of used actions
INFO [2018-09-10 15:46:21.17]: ------------------------------
INFO [2018-09-10 15:46:21.17]: --- Step: default_platform ---
INFO [2018-09-10 15:46:21.17]: ------------------------------
INFO [2018-09-10 15:46:21.17]: Driving the lane 'ios test_cert_migration' 🚀
INFO [2018-09-10 15:46:21.17]: -----------------------------------
INFO [2018-09-10 15:46:21.17]: --- Step: match_certs_migration ---
INFO [2018-09-10 15:46:21.17]: -----------------------------------
INFO [2018-09-10 15:46:21.31]: Action: match_certs_migration Params: username => xxxxxx@xxxx.com app_identifier => xxxxx.xxx  type => adhoc
Loading session from '/Users/Tunde/.fastlane/spaceship/jamesadegoroye@ymail.com/cookie'
INFO [2018-09-10 15:46:24.17]: all_certs_disr -> /var/folders/ct/gsm1gpw96nsc1qrr2z4x3nd80000gp/T/d20180910-44515-alygik
INFO [2018-09-10 15:46:24.17]: current_git_dir -> /var/folders/ct/gsm1gpw96nsc1qrr2z4x3nd80000gp/T/d20180910-44515-1k1lt7i
INFO [2018-09-10 15:46:24.17]: $ git clone 'https://tunds@bitbucket.org/tunds/fastlane-example-certificates.git' '/var/folders/ct/gsm1gpw96nsc1qrr2z4x3nd80000gp/T/d20180910-44515-1k1lt7i'
INFO [2018-09-10 15:46:24.19]: ▸ Cloning into '/var/folders/ct/gsm1gpw96nsc1qrr2z4x3nd80000gp/T/d20180910-44515-1k1lt7i'...
INFO [2018-09-10 15:46:33.36]: ▸ remote: Counting objects: 68, done.
INFO [2018-09-10 15:46:33.95]: ▸ remote: Total 68 (delta 0), reused 0 (delta 0)
INFO [2018-09-10 15:46:33.95]: ▸ Unpacking objects: 100% (68/68), done.
/Users/Tunde/Documents/Fastlane/fastlaneexample/fastlane/actions/match_certs_migration.rb:94: warning: conflicting chdir during another chdir block
INFO [2018-09-10 15:46:33.97]: $ git branch -a | grep remotes | grep -v HEAD | grep -v master

ERROR [2018-09-10 15:46:33.99]: Exit status: 1
WARN [2018-09-10 15:46:33.99]: Lane Context:
INFO [2018-09-10 15:46:33.99]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios test_cert_migration"}
ERROR [2018-09-10 15:46:33.99]: Exit status: 1
INFO [2018-09-10 15:46:33.99]: Successfully generated documentation at path '/Users/Tunde/Documents/Fastlane/fastlaneexample/fastlane/README.md'

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | opt_out_usage              | 0           |
| 3    | default_platform           | 0           |
| 💥   | match_certs_migration      | 12          |
+------+----------------------------+-------------+

DEBUG [2018-09-10 15:46:34.00]: All plugins are up to date
ERROR [2018-09-10 15:46:34.00]: fastlane finished with errors
DEBUG [2018-09-10 15:46:34.01]: All plugins are up to date
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] Exit status: 1
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane_core/lib/fastlane_core/command_executor.rb:90:in `execute'
  /Users/Tunde/Documents/Fastlane/fastlaneexample/fastlane/actions/match_certs_migration.rb:146:in `git_command_executor'
  /Users/Tunde/Documents/Fastlane/fastlaneexample/fastlane/actions/match_certs_migration.rb:96:in `get_all_certs'
  /Users/Tunde/Documents/Fastlane/fastlaneexample/fastlane/actions/match_certs_migration.rb:27:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
  Fastfile:33:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.104.0/bin/fastlane:20:in `<top (required)>'
  /usr/local/bin/fastlane:22:in `load'
  /usr/local/bin/fastlane:22:in `<top (required)>'

**Comment by HIIgor** [comment]
@tundsD53  it seems that you execute the fastlane with bundler? You can google how to solve the problem.


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by HIIgor** [comment]
@tundsD53  I'm sorry that I closed the issue by accident yesterday.

 I tried the command once. I found that the action may be aborted by the git `git branch -a | grep remotes | grep -v HEAD | grep -v master`. 

Could you please execute the git command as this plugin does  ?
```
INFO [2018-09-11 10:35:02.85]: $ git clone 'your repo git url' '/var/folders/z2/_0q3f57d7rsgpj8f9dyzh4cr0000gn/T/d20180911-4391-gah5r'
INFO [2018-09-11 10:35:02.87]: ▸ Cloning into '/var/folders/z2/_0q3f57d7rsgpj8f9dyzh4cr0000gn/T/d20180911-4391-gah5r'...
INFO [2018-09-11 10:35:03.74]: ▸ remote: Counting objects: 121, done.
INFO [2018-09-11 10:35:03.78]: ▸ remote: Compressing objects: 100% (82/82), done.
INFO [2018-09-11 10:35:04.21]: ▸ remote: Total 121 (delta 13), reused 109 (delta 11)
INFO [2018-09-11 10:35:04.21]: ▸ Receiving objects: 100% (121/121), 150.84 KiB | 353.00 KiB/s, done.
INFO [2018-09-11 10:35:04.21]: ▸ Resolving deltas: 100% (13/13), done.

INFO [2018-09-11 10:35:04.22]: $ cd /var/folders/z2/_0q3f57d7rsgpj8f9dyzh4cr0000gn/T/d20180911-4391-gah5r

INFO [2018-09-11 10:35:04.23]: $ git branch -a | grep remotes | grep -v HEAD | grep -v master
INFO [2018-09-11 10:35:04.25]: ▸ remotes/origin/com.XXXXXXX.1403.appstore
INFO [2018-09-11 10:35:04.25]: ▸ remotes/origin/com.XXXXXXX.C2BInhouse.enterprise
INFO [2018-09-11 10:35:04.25]: ▸ remotes/origin/com.XXXXXXX.inhouse.enterprise
INFO [2018-09-11 10:35:04.25]: ▸ remotes/origin/com.XXXXXXX.ios.baomai.manager.enterprise
INFO [2018-09-11 10:35:04.25]: ▸ remotes/origin/com.XXXXXXX.ios.cardelivery.enterprise
INFO [2018-09-11 10:35:04.26]: ▸ remotes/origin/com.XXXXXXX.ios.dev.baomai.manager.development
INFO [2018-09-11 10:35:04.26]: ▸ remotes/origin/com.XXXXXXX.ios.test.baomai.manager.enterprise
INFO [2018-09-11 10:35:04.26]: ▸ remotes/origin/com.XXXXXXX.XXXXXXX.dev.development
INFO [2018-09-11 10:35:04.26]: ▸ remotes/origin/com.xxxxxxx.1436.appstore

INFO [2018-09-11 10:35:04.26]: $ git checkout '.'
INFO [2018-09-11 10:35:04.27]: $ git checkout remotes/origin/com.XXXXXXX.1403.appstore
```

or have you configured the git by using `git config`?

**Comment by HIIgor** [comment]
#1  It seems to be the same issue. I am trying to reproduce this problem by using a  new machine, I am wondering if there were something wrong with git configuration.

**Comment by tundsD53** [comment]
@HIIgor Cool just keep this open and me posted once you've figured out the issue mate.

**Comment by tundsD53** [comment]
@HIIgor Any updates on this?
